name: todo

packages:
  - packages/*

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: melos exec -c 1 -- "flutter analyze . --fatal-infos"
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -c 1 -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  build_runner:build:select:
    run: melos exec -c 1 --depends-on="build_runner" -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run `flutter pub run build_runner build` for a specific package in this project
    select-package:
      flutter: true
      depends-on: build_runner

  build_runner:build:
    run: melos run build_runner:build:select --no-select
    description: Run `flutter pub run build_runner build` for all files in this project

  test:select:
    run: melos exec -c 1 --dir-exists="test" --fail-fast -- "flutter test" --no-pub --coverage
    description: Run `flutter test` for a specific package in this project
    select-package:
      flutter: true
      dir-exists: test

  test:
    run: melos run test:select --no-select
    description: Run `flutter test` in all packages

