name: todo
description: Main package handling todo app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: packages/core
  redux_core:
    path: packages/redux_core
  ui:
    path: packages/ui
  locale:
    path: packages/locale
  notes:
    path: packages/notes
  auth:
    path: packages/auth

  cupertino_icons: ^1.0.5
  firebase_core: ^2.6.1
  go_router: ^6.0.8
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true