name: core
description: Package to handle central logic.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.4.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  fpdart: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: